# Generated by Django 3.2.14 on 2022-08-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_weight_dependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_dependency',
        ),
    ]
