# Generated by Django 3.2.14 on 2022-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220826_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_dependency',
            field=models.BooleanField(default=False, verbose_name='عدم وابستگی محصول به وزن'),
        ),
    ]
