# Generated by Django 3.2.14 on 2022-08-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_weight_dependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_dependency',
        ),
        migrations.AddField(
            model_name='productidentity',
            name='weight_dependency',
            field=models.BooleanField(default=False, verbose_name='عدم وابستگی محصول به وزن'),
        ),
    ]
