# Generated by Django 3.2.14 on 2022-08-27 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productidentity_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidentity',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد باقی مانده در انبار'),
        ),
    ]
