# Generated by Django 3.2.14 on 2022-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productidentity_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productidentity',
            name='stock',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='موقعبت مکانی'),
        ),
    ]
