# Generated by Django 3.2.14 on 2022-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20220827_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محصول'),
        ),
    ]
